version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: webmail_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: meu_webmail
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: webmail_php
    volumes:
      - ./src:/var/www/html
    environment:
      - MAIL_SERVER=10.0.0.1

  web:
    image: nginx:alpine
    container_name: webmail_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app